/*
 * Explore API
 * The Opendatasoft [Explore API v2](https://help.opendatasoft.com/apis/ods-explore-v2/) is organized around REST. It provides access to all the data available through the platform in a coherent, hierarchical way.  - Only the HTTP `GET` method is supported. - All API endpoints return JSON. - Endpoints are organized in a hierarchical way describing the relative relationship between objects. - All responses contain a list of links allowing easy and relevant navigation through the API endpoints. - All endpoints use the [Opendatasoft Query Language (ODSQL)](https://help.opendatasoft.com/apis/ods-explore-v2/#section/Opendatasoft-Query-Language-(ODSQL)). This means that, most of the time, parameters work the same way for all endpoints.
 *
 * The version of the OpenAPI document: V2
 * Contact: support@opendatasoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetDatasets429Response
 */
public class GetDatasets429ResponseTest {
    private final GetDatasets429Response model = new GetDatasets429Response();

    /**
     * Model tests for GetDatasets429Response
     */
    @Test
    public void testGetDatasets429Response() {
        // TODO: test GetDatasets429Response
    }

    /**
     * Test the property 'errorcode'
     */
    @Test
    public void errorcodeTest() {
        // TODO: test errorcode
    }

    /**
     * Test the property 'resetTime'
     */
    @Test
    public void resetTimeTest() {
        // TODO: test resetTime
    }

    /**
     * Test the property 'limitTimeUnit'
     */
    @Test
    public void limitTimeUnitTest() {
        // TODO: test limitTimeUnit
    }

    /**
     * Test the property 'callLimit'
     */
    @Test
    public void callLimitTest() {
        // TODO: test callLimit
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
